### ISSUE TITLE
Correcting typos in the remote origin URL text field.

### ISSUE THREAD

**Issue by mattrltrent** [mattrltrent/github_painter#2]
Very often people enter a wrong version of this field:

<img width="775" alt="Screenshot 2024-06-05 at 6 12 11 PM" src="https://github.com/mattrltrent/github_painter/assets/69698360/811206cc-96df-494f-be29-015d28ea9123">

Like, *very often* (>50% of the time) they forget the `.git` extension or don't prefix it with `https://`. Some regex could be added to auto fix this issue.

**Comment by RamanaRaj7** [comment]
isn't this solved?

**Comment by mattrltrent** [comment]
Mostly, yes. However, sometimes users enter repo URLs in the form: `github.com/username/repo` and forget the `https://` prefix.

Ideally, the code would do a quick check using Regex to see if the URL entered already has `https://` before it, and if not, add it.

Moreover, instead of indiscriminately adding `.git` to the end of every URL, the code would again check with Regex to see if the user entered a `.git` postfix or not and then choose to add `.git` or not at the end accordingly.

**Comment by RamanaRaj7** [comment]
ooh ok got it.
